// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-fetch';
import type { PingData, PingResponse, ContentTypesData, ContentTypesResponse } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class CatalogPluginService {
    public static ping<ThrowOnError extends boolean = false>(options?: Options<PingData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<PingResponse, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/catalogplugin/api/v1/ping',
            ...options
        });
    }

    public static getContentTypes<ThrowOnError extends boolean = false>(options?: Options<ContentTypesData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<ContentTypesResponse, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/catalogplugin/api/v1/content-types',
            ...options
        });
    }
}