// This file is auto-generated by @hey-api/openapi-ts
export type PingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/hackclient/api/v1/ping';
};

export type PingErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type PingResponses = {
    /**
     * OK
     */
    200: string;
};

export type PingResponse = PingResponses[keyof PingResponses];

export type ContentTypesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/catalogplugin/api/v1/content-types';
};

export type ContentTypesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export interface PropertyTypeDto {
    id: number;
    key: string;
    alias: string;
    name: string;
    description: string;
    mandatory: boolean;
    dataTypeId: number;
    dataTypeKey: string;
    sortOrder: number;
}

export interface PropertyGroupDto {
    id: number;
    key: string;
    name: string;
    alias: string;
    sortOrder: number;
    propertyTypes: PropertyTypeDto[];
}

export interface ContentTypeDto {
    id: number;
    key: string;
    alias: string;
    name: string;
    description: string;
    icon: string;
    isElement: boolean;
    allowedAsRoot: boolean;
    propertyGroups: PropertyGroupDto[];
}

export type ContentTypesResponses = {
    /**
     * OK
     */
    200: ContentTypeDto[];
};

export type ContentTypesResponse = ContentTypesResponses[keyof ContentTypesResponses];

export interface DataTypeDto {
    id: number;
    key: string;
    name: string;
    editorAlias: string;
    databaseType: string;
}

export interface PropertyTypeDetailDto extends PropertyTypeDto {
    validationRegExp: string;
    dataType: DataTypeDto;
}

export interface PropertyGroupDetailDto extends PropertyGroupDto {
    propertyTypes: PropertyTypeDetailDto[];
}

export interface ContentTypeReferenceDto {
    id: number;
    key: string;
    alias: string;
    name: string;
    icon: string;
}

export interface AllowedContentTypeDto {
    id: number;
    alias: string;
    sortOrder: number;
}

export interface ContentTypeDetailDto extends ContentTypeDto {
    compositions: ContentTypeReferenceDto[];
    allowedContentTypes: AllowedContentTypeDto[];
    createDate: string;
    updateDate: string;
    defaultTemplate: string;
    propertyGroups: PropertyGroupDetailDto[];
}

export type ContentTypeDetailData = {
    body?: never;
    path: {
        alias: string;
    };
    query?: never;
    url: '/umbraco/catalogplugin/api/v1/content-types/{alias}';
};

export type ContentTypeDetailErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Content type not found
     */
    404: unknown;
};

export type ContentTypeDetailResponses = {
    /**
     * OK
     */
    200: ContentTypeDetailDto;
};

export type ContentTypeDetailResponse = ContentTypeDetailResponses[keyof ContentTypeDetailResponses];

export type ClientOptions = {
    baseUrl: 'https://localhost:44389' | (string & {});
};
